-keep class ca.marklauman.tools.** { *; }
-keep interface ca.marklauman.tools.** { *; }
-keep public class ca.marklauman.tools.**$** { *; }
-keep public interface ca.marklauman.tools.**$** { *; }
-keep class com.example.android.common.view.SlidingTabLayout
-keep public interface com.example.android.common.view.SlidingTabLayout$TabColorizer { *; }
-keepattributes Signature, InnerClasses